# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5206de57a053f5596ee221aa6d2e6000494c88591e23bab8e99120cb98f6a5ee6c8fb4f5c8c4e90d6dfb3bcba0f95cf519a3a2358a31f2a2578bd36329f4b134

test:
  secret_key_base: 18f32fb06c7880f6d22711fc03f8eceed53dff55cb4f103157548a422615a71752603c7e3a93a61c00f37f250845b0448a09a28bed8f7ddf88fc92edd4a589a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
